syntax = "proto3";

package casper;

message BlockMessage {
  bytes block_hash = 1;
  BlockHeader header = 2;
  BlockBody body = 3;
  repeated Justification justifications = 4;
  bytes sender = 5;
  int64 seq_num = 6;
  bytes sig = 7;
  string sig_algorithm = 8;
  string shard_id = 9;
  bytes extra_bytes = 10;
}

message BlockHeader {
  repeated bytes parents = 1;
  bytes sender = 2;
  string sig_algorithm = 3;
  bytes sig = 4;
  string shard_id = 5;
  int64 seq_num = 6;
  int32 version = 7;
  bytes body_hash = 8;
  bytes block_hash = 9;
  int64 dag_level = 10;
  repeated Justification justifications = 11;
}

message BlockBody {
  repeated ProcessedDeploy deploys = 1;
  repeated ProcessedSystemDeploy system_deploys = 2;
  RChainState state = 3;
}

message RChainState {
  bytes pre_state_hash = 1;
  bytes post_state_hash = 2;
  repeated Bond bonds = 3;
  int64 block_number = 4;
}

message ProcessedDeploy {
  DeployData deploy = 1;
  PCost cost = 2;
  repeated Event deploy_log = 3;
  repeated Event payments_results = 4;
  bool is_failed = 5;
  string system_deploy_error = 6;
}

message ProcessedSystemDeploy {
  oneof system_deploy {
    CloseBlockDeploy close_block_deploy = 1;
    SlashSystemDeploy slash_system_deploy = 2;
  }
}

message CloseBlockDeploy {}

message SlashSystemDeploy {
  bytes invalid_block_hash = 1;
  bytes issuer_public_key = 2;
}

message Event {
  oneof event_instance {
    ProduceEvent produce = 1;
    ConsumeEvent consume = 2;
  }
}

message ProduceEvent {
  bytes channel_hash = 1;
  bytes data = 2;
  bool persistent = 3;
}

message ConsumeEvent {
  repeated bytes channel_hashes = 1;
  bytes data = 2;
  bool persistent = 3;
}

message PCost {
  uint64 cost = 1;
}

message Bond {
  bytes validator = 1;
  int64 stake = 2;
}

message Justification {
  bytes validator = 1;
  bytes latest_block_hash = 2;
}

message DeployData {
  bytes deployer = 1;
  string term = 2;
  int64 timestamp = 3;
  bytes sig = 4;
  string sig_algorithm = 5;
  int64 phlo_price = 7;
  int64 phlo_limit = 8;
  int64 valid_after_block_number = 10;
  string shard_id = 11;
}
